# <span style="color:#0b486b">  FIT5215: Deep Learning (2021)</span>
***
*CE/Lecturer:*  **Dr Trung Le** | trunglm@monash.edu <br/>
*Head TA:*  **Dr Van Nguyen** | van.nguyen1@monash.edu <br/>
*Tutor:* **Mr Anh Bui** \[tuananh.bui@monash.edu\] | **Mr Tuan Nguyen**  \[tuan.ng@monash.edu \] | **Dr Binh Nguyen** \[binh.nguyen1@monash.edu\] | **Dr Mahmoud Mohammad** \[mahmoud.hossam@monash.edu\]
<br/> <br/>
Faculty of Information Technology, Monash University, Australia
***

# <span style="color:#0b486b">Tutorial 1: Deep Learning with TensorFlow</span> #
**The purpose of this tutorial is to demonstrate how to work with an open source software library for developing deep neural networks apllications, called TensorFlow (TF). In this tutorial, we present the following topics:**

1. A quick tour of TensorFlow 1.x
2. How to visualize a computational graph and its node values using Tensorboard.
3. Advancements of TensorFlow 2.x in comparison to TensorFlow 1.x.

**The tutorial material and code are mainly prepared in TensorFlow 1.x, which involves a low-level programming compared to TensorFlow 2.x to support students in being aware of how TF works and what is under the scene. If students master TF 1.x, it is very convenient and easy to move to TF 2.x. In addition, to facilitate the study of the students, the tutorial content also has additional material to indicate how the TF 1.x code can be ported to that of TF 2.x.** 

**References and additional reading and resources**
- [Installing Tensorflow on Windows](https://www.tensorflow.org/install/install_windows)
- [Tensorflow API documentations](https://www.tensorflow.org/versions/master/api_docs/python/)
- [Examples with Tensorflow](https://www.tensorflow.org/versions/master/get_started/)

**Acknowledgement**: *Some materials used in this tutorial have been adapted from Chapter 3 of the the book "Learning TensorFlow: A Guide to Building Deep Learning Systems" by Hope, Resheff and Lieder and Chapter 2 of "Deep Learning with with TensorFlow 2 and Keras" by Antonio Culli, Amita Kapoor, Sujit Pal.*

---

## <span style="color:#0b486b"> I. A quick tour of TensorFlow 1.x </span>

### <span style="color:#0b486b"> I.1 Computational Graph </span> ###
Computational graph is a basic concept of TensorFlow which represents the functional dependency of nodes. The following figure presents a typical computational graph wherein each node is a tensor. <br/>

<img src="images/ComputationalGraph.png" width="500" align="center"/> 
The above computational graph presents some functional dependencies:
- $c$ is dependent on $a$, $b$.
- $d$ depends on $a$, $e$ depends on $c$.
- $f$ depends on $d$, $e$.


### <span style="color:#0b486b"> I.2 Declare a Computational Graph </span>
The following code snippet shows how to declare a computational graph in TensorFlow. Once we import TF, a specific `empty default graph` is formed. All the nodes we create are automatically associated with that default graph. It is worth noting that we just `declare a graph` and **nothing** has been executed yet.

Below we import TensorFlow 2.x. To ensure that this is comparatible and works with TF 1.x codes, we need to import the coressponding package `tensorflow.compat.v1`.




In [1]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

Instructions for updating:
non-resource variables are not supported in the long term


In [2]:
a = tf.constant(5)
b = tf.constant(2)
c = tf.constant(3)
d = tf.multiply(a,b)
e = tf.add(b,c)
f = tf.subtract(d,e)

**<span style="color:red">Exercise 1</span>**: Draw the computational graph of the above computational process.

<img src="sol/tut1-e1.png" width="500" align="center"/>

### <span style="color:#0b486b"> I.3 Fetches Values </span> ###
To query the nodes in a computational graph, we create a `session` and run a query in this sesstion.

In [3]:
with tf.Session() as sess:
    fetches = [a,b,c,d,e,f]
    outs = sess.run(fetches)
    print("outs={}".format(outs))

outs=[5, 2, 3, 10, 5, 5]


**<span style="color:red">Exercise 2</span>**: Write code in the cell below to create a new node $g = a^2 + (b * f)$ and $h= (b+c)*d + e^2*c$, create a session, run a query to compute and display the values of $g$ and $h$.

In [4]:
with tf.Session() as sess: 
    g = a*a + b*f 
    h = (b+c)*d + e*e*c 
    print("g={}".format(sess.run(g)))
    print("h={}".format(sess.run(h)))
    assert(g.eval()==sess.run(g))
    assert(h.eval()==sess.run(h))

g=35
h=125


### <span style="color:#0b486b"> I.4 More about Graph </span> ###
Each TF project is associated with a default computational graph. Besides the default graph, we can create other graphs on demand and work with these graphs.

In [10]:
g1= tf.get_default_graph()
g2 = tf.Graph()
print(g1 is tf.get_default_graph())
with g2.as_default():
    print(g1 is tf.get_default_graph())
    print(g2 is tf.get_default_graph())

True
False
True


### <span style="color:#0b486b"> I.5 Data Types and Cast </span> ###
TensorFlow supports several data types when declaring its nodes. We can cast a node from a data type to another. 

In [11]:
x = tf.constant(name="x", value=[1,2,3], dtype= tf.int32)
print("x type is {}".format(x.dtype))
y = tf.cast(x, tf.float32)
print("y type is {}".format(y.dtype))

x type is <dtype: 'int32'>
y type is <dtype: 'float32'>


Below are the popular data types in TensorFlow.

<img src="images/TF_DataTypes.png" width="600" align="center"/>

### <span style="color:#0b486b">I.6 Get Shape </span> ###
Each node in a computational graph of TensorFlow is a tensor. We can use the method `get_shape()` to get shape of a tensor. Note that we create an interactive session and use `x.eval()` to evaluate the value of node `x` in the computational graph.

In [12]:
x= tf.constant([[[1,2,3],[4,5,6]],
                [[-1,-2,-3],[-4,-5,-6]]])
sess = tf.InteractiveSession()
print("x= {}".format(x.eval()))
print("x shape: {}".format(x.get_shape()))
sess.close()

x= [[[ 1  2  3]
  [ 4  5  6]]

 [[-1 -2 -3]
  [-4 -5 -6]]]
x shape: (2, 2, 3)


## <span style="color:#0b486b"> I.7 Initialize Tensors </span> ###
When declaring nodes in TensorFlow, we can initialize them using a heap of methods offered by TensorFlow. After that we can querry their values in an `interactive session`.

In [13]:
a= tf.constant(name='a', value=3)
b= tf.fill(name='b', dims= [2,3], value=-1)
c= tf.zeros(name='c', shape= [2,3])
d= tf.ones(name='d', shape=[2,3])
e= tf.random_normal(name='e', shape=[2,3], mean=0, stddev=1)
f= tf.ones_like(e)
g= tf.zeros_like(e)
h= tf.random_shuffle([5,10,15,20])
k= tf.random_uniform([2,3], minval=-1, maxval=1)

In [14]:
sess= tf.InteractiveSession()
print("a={}".format(a.eval()))
print("b={}".format(b.eval()))
print("c={}".format(c.eval()))
print("d={}".format(d.eval()))
print("e={}".format(e.eval()))
print("f={}".format(f.eval()))
print("g={}".format(g.eval()))
print("h={}".format(h.eval()))
print("k={}".format(k.eval()))
sess.close()

a=3
b=[[-1 -1 -1]
 [-1 -1 -1]]
c=[[0. 0. 0.]
 [0. 0. 0.]]
d=[[1. 1. 1.]
 [1. 1. 1.]]
e=[[ 0.3291204   0.68639845 -0.5126701 ]
 [ 0.64776415  0.23761442 -1.6916677 ]]
f=[[1. 1. 1.]
 [1. 1. 1.]]
g=[[0. 0. 0.]
 [0. 0. 0.]]
h=[10  5 20 15]
k=[[ 0.25113034  0.37511373  0.90871096]
 [ 0.12821078 -0.7738824  -0.8114779 ]]


### <span style="color:#0b486b"> I.8 Matrix Multiplication and Activation </span> ###
Matrix multiplication in conjunction with activation is a building block in deep learning. In the following code snippet, we declare the matrix $A$ of $(2,3)$ and a vector $x$ of $(3,)$. To be able to apply $A \times x$, we need to expand $x$ one dimension via the method `tf.expand_dims()`. Now $x$ has shape $(3,1)$ and we can do a matrix multiplication. Finnaly, we apply the activation function ReLu over the output of matrix multiplication: $ReLu(A \times x)$. In addition, the formulation of ReLu is $ReLu(t)= \max\{0,t\}$, which is the most popular activation function in deep learning.

In [15]:
A = tf.constant([[1,2,3],
                 [-4,-5,-6]])
x= tf.constant([1,1,1])
print("A shape: {}".format(A.get_shape()))
print("x shape: {}".format(x.get_shape()))
x= tf.expand_dims(x,1) # expand one dimension to turn x's shape into (3, 1) 
print("x shape: {}".format(x.get_shape()))
sess= tf.InteractiveSession()
y =tf.matmul(A,x)
print("y before activation: {}".format(y.eval()))
y= tf.nn.relu(y)
print("y after activation: {}".format(y.eval()))
sess.close()

A shape: (2, 3)
x shape: (3,)
x shape: (3, 1)
y before activation: [[  6]
 [-15]]
y after activation: [[6]
 [0]]


In [16]:
x= tf.expand_dims(x,1)
print("x shape: {}".format(x.get_shape()))

x shape: (3, 1, 1)


**<span style="color:red">Exercise 3</span>**: Create a tensor $x$ of shape $(3, 1)$ with entry values $x[i, 0]=i$, $\forall i = 0, 1, 2$ and another tensor $y$ of shape $(1, 3)$ with all entry values of $2$. Create another operation $z$ to perform matrix multiplication of $x$ and $y$. This operation is also called outer product. Print the shape of $z$. Also, run a querry to compute $z$ and print the result.

In [24]:
# your code here
x = tf.constant([[0],[1],[2]])
y = tf.constant([[2,2,2]])
z = tf.matmul(x,y)
with tf.Session() as sess: 
    print(x.get_shape())
    print(y.get_shape())
    print(z.eval())

(3, 1)
(1, 3)
[[0 0 0]
 [2 2 2]
 [4 4 4]]


### <span style="color:#0b486b">I.9 Name </span> ###
Each tensor object also has an identifying name. This name is an *intrinsic* string name. We can use the `object.name` attribute to see the name of the object.
Objects residing within the same graph cannot have the same name.


TF will automatically add an underscore and a number to distinguish the two which accidentally have the same name. Both objects can have the same name when they are associated with different graphs.

In [25]:
tf.reset_default_graph()
g = tf.get_default_graph()
with g.as_default():
    c1= tf.constant(name='c', value=3)
    c2= tf.constant(name='c', value=5)
print("c1 name: {}".format(c1.name))
print("c2 name: {}".format(c2.name))

c1 name: c:0
c2 name: c_1:0


### <span style="color:#0b486b">I.10 Name Scope </span> ### 
Name scope is a *hierarchically group nodes* together by name to divide a graph into subgraphs with some semantic meaning. To declare a name space, we use the syntax: `tf.name_scope("prefix")`.

Organizing your TensorFlow code using name scopes shows some advantages:
- Make it easier to follow and manage.
- Visualization of the graph structure.
- Useful when dealing with a large, complicated graph.

In [26]:
with tf.get_default_graph().as_default():
    c1 = tf.constant(name= "c", value=1.0)
    with tf.name_scope("prefix"):
        c2 = tf.constant(name= "c", value=2.0)
        c3 = tf.constant(name= "c", value=3.0)
print("c1 name: {}".format(c1.name))
print("c2 name: {}".format(c2.name))
print("c3 name: {}".format(c3.name))

c1 name: c_2:0
c2 name: prefix/c:0
c3 name: prefix/c_1:0


### <span style="color:#0b486b">I.11 Variable </span> ### 
Variable nodes are crucial nodes in a TensorFlow computational graph whose values can be *modified* and *changed*. 

In a deep learning model, `model parameters` are declared as `variable nodes` in the relevant computational graph whose values are modified during training course. Using variables is done in two stages:
- Call the `tf.Variable()` function to create a variable and define what value it will be initialized with.
- Explicitly perform an initialization operation by running the session with the `tf.global_variables_initializer()` method. This will allocate the memory for the variable and set its initial values.



In [27]:
init_var = tf.random.normal(shape=[2,3], mean=0, stddev=0.1, dtype= tf.float32)
my_var=  tf.Variable(initial_value= init_var, name='x')
init= tf.global_variables_initializer()
print("Pre-run my_var: {}".format(my_var))
with tf.Session() as sess:
    sess.run(init)
    my_var = sess.run(my_var)
    print("Post-run my_var: {}".format(my_var))

Pre-run my_var: <tf.Variable 'x:0' shape=(2, 3) dtype=float32_ref>
Post-run my_var: [[-0.11726787 -0.07957689  0.08123686]
 [ 0.01206291 -0.17473172  0.08374216]]


Below presents some popular ways to *randomly initialize* the intial values of variables.

<img src="images/tf_random.png" width="800" align="center"/>


### <span style="color:#0b486b">I.12 Variable Scope and Reuse Variable </span> ###  

Sometimes we might want to reuse a variable. This can be done by `tf.get_variable()`, which either reuses the variable with a specified name or creates a new variable with the name if it is not created before.

If we want to reuse a variable later, we first need to declare this in a variable scope with `tf.variable_scope()` and then in this variable scope invoke `tf.get_variable()` with the flag reuse to be set to `True`.

In [28]:
with tf.variable_scope("layer1"):
    W1= tf.get_variable(name='W', shape=[2,3], dtype= tf.float32, initializer= tf.initializers.random_normal(0,0.1))
    x= tf.Variable(initial_value=tf.random_normal([4,2], 0, 0.1), name="x")
    v1= tf.matmul(x, W1)

with tf.variable_scope("layer1", reuse=True):
    W2= tf.get_variable(name='W', shape=[2,3], dtype= tf.float32, initializer= tf.initializers.random_normal(0,0.2))

diff = tf.subtract(W1,W2)
norm_diff = tf.norm(diff, ord='euclidean')
init = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(init)
    norm_diff= sess.run(norm_diff)

if norm_diff==0:
    print("W1 and W2 are tight")
else:
    print("W1 and W2 are not tight")

W1 and W2 are tight


### <span style="color:#0b486b">I.13 Name Scope & Variable Scope </span> ###   
There are two different types of scopes: `name scope` created using `tf.name_scope` and `variable scope` created using `tf.variable_scope`. Both scopes have the same effect on all operations as well as variables created using `tf.Variable`, while only variable scope affects on `tf.get_variable()`

The following figure shows the difference of two ways to create variables: `tf.Variable` and `tf.get_variable()`. <br/>

<img src="images/Compare2WaysVariables.png" width="400" align="center"/>

In [29]:
tf.reset_default_graph()
with tf.name_scope("ns"):
    with tf.variable_scope("vs", reuse=tf.AUTO_REUSE):
        c1= tf.Variable(name="c", initial_value= tf.constant(1.0))
        c2= tf.get_variable(name="c", initializer= tf.constant([-1,1]))
print("c1 name: {}".format(c1.name))
print("c2 name: {}".format(c2.name))

c1 name: ns/vs/c:0
c2 name: vs/c:0


**<span style="color:red">Exercise 4</span>**: TensorFlow can also automatically decide to create a new variable if it does not exist and reuse if it is already created by setting `reuse=tf.AUTO_REUSE` as shown in the function `linear()` below. Questions:

(a) What is the value of `diff`? You can run a session to compute its value to answer this question.

(b) Why does `diff` get that value?

(c) What happens if we set `reuse=False` in the delaration of `z` in the code below? Why?

In [40]:
tf.reset_default_graph()

def linear(x, output_dim, reuse=tf.AUTO_REUSE):
    with tf.variable_scope("linear", reuse=reuse):
        W = tf.get_variable('weights', shape=[output_dim, x.get_shape()[0]], dtype=tf.float32)
        output = tf.matmul(W, x)
        return output
    
x = tf.constant(0.0, shape=(3, 1))
y = linear(x, 3, reuse=tf.AUTO_REUSE)
z = linear(x, 3, reuse=tf.AUTO_REUSE)
diff = y - z

init = tf.global_variables_initializer()
with tf.Session() as sess: 
    sess.run(init)
    print('x={}'.format(sess.run(x)))
    print('diff={}'.format(sess.run(diff)))

# To get the names of all tensor in the default graph 
# for op in tf.get_default_graph().get_operations():
#     print(str(op.name))
    
# To get all variables
# for var in tf.global_variables(): 
#     print(var.name)

[[0.]
 [0.]
 [0.]]
[[-0.]
 [-0.]
 [-0.]]
Const
linear/weights/Initializer/random_uniform/shape
linear/weights/Initializer/random_uniform/min
linear/weights/Initializer/random_uniform/max
linear/weights/Initializer/random_uniform/RandomUniform
linear/weights/Initializer/random_uniform/sub
linear/weights/Initializer/random_uniform/mul
linear/weights/Initializer/random_uniform
linear/weights
linear/weights/Assign
linear/weights/read
linear/MatMul
linear_1/MatMul
sub
init


**Write your answer here:**

(a)

(b)

(c)

### <span style="color:#0b486b">I.14 Place Holder </span> ###    
Placeholders can be thought of as `empty variables` that will be filled with data later on.

We use them when constructing our graph and when executing querying value of nodes, we need to feed them with the input data.


In [17]:
import numpy as np

tf.reset_default_graph()
x_data= np.random.rand(10,3)

with tf.name_scope("layer1"):
    W = tf.Variable(name= "W", initial_value=tf.random.normal([1,10],0,0.1, dtype= tf.float32))
    b = tf.Variable(name="b", initial_value=tf.random.normal([1,3],0,0.1, dtype=tf.float32))
    x = tf.placeholder(name="x", shape=[10,3], dtype= tf.float32)
    v = tf.matmul(W,x) + b
    s = tf.reduce_mean(v)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    s= sess.run(s, feed_dict={x:x_data})

print("s= {}".format(s))

s= 0.06081658601760864


 ### <span style="color:#0b486b">I.16 Save and Restore Model </span> ###   
 It is very convenient to save a model to hard disk and then restore that model in TensorFlow as shown below:

In [18]:
import os
tf.reset_default_graph()

# Create some variables.
v1 = tf.get_variable("v1", shape=[3], initializer = tf.zeros_initializer)
v2 = tf.get_variable("v2", shape=[5], initializer = tf.zeros_initializer)

inc_v1 = v1.assign(v1+1)
dec_v2 = v2.assign(v2-1)

# Add an op to initialize the variables.
init_op = tf.global_variables_initializer()

# Add ops to save and restore all the variables.
saver = tf.train.Saver()

# Later, launch the model, initialize the variables, do some work, and save the
# variables to disk.
with tf.Session() as sess:
    sess.run(init_op)
    # Do some work with the model.
    inc_v1.op.run()
    dec_v2.op.run()
    if not os.path.exists(os.path.abspath("./models/tmp")):
        os.makedirs(os.path.abspath("./models/tmp"))
    # Save the variables to disk.
    save_path = saver.save(sess, "./models/tmp/model.ckpt")
    print("Model saved in path: %s" % save_path)

Model saved in path: ./models/tmp/model.ckpt


In [3]:
tf.reset_default_graph()

# Create some variables.
v1 = tf.get_variable("v1", shape=[3])
v2 = tf.get_variable("v2", shape=[5])

# Add ops to save and restore all the variables.
saver = tf.train.Saver()

# Later, launch the model, use the saver to restore variables from disk, and
# do some work with the model.
with tf.Session() as sess:
    # Restore variables from disk.
    saver.restore(sess, "./models/tmp/model.ckpt")
    print("Model restored.")
    # Check the values of the variables
    print("v1 : %s" % v1.eval())
    print("v2 : %s" % v2.eval())

INFO:tensorflow:Restoring parameters from ./models/tmp/model.ckpt
Model restored.
v1 : [1. 1. 1.]
v2 : [-1. -1. -1. -1. -1.]


### <span style="color:#0b486b">I.17. Visualization with TensorBoard</span>

##### <span style="color:#0b486b"> Logging and creating summary for visualization </span>

Usually one would use the `print()` function and `matplotlib` to visualize progress during training. There is a better way to do this via TensorBoard. If you feed in training stats, it will display nice interactive visualizations of
these stats in your web browser (e.g., learning curves).

You can also provide the graph’s definition and TensorBoard provides interface to browse through it. This is very useful to identify errors in the graph, to find bottlenecks, and so on.

Let's visualize learning rate and global step in the example above.

In [20]:
# construction
tf.reset_default_graph()

starter_lr = 1.
decay_rate = 0.9
global_step = tf.Variable(0., trainable=0)
incr = tf.assign(global_step, global_step + 1)

with tf.control_dependencies([incr]):
    learning_rate = starter_lr * tf.pow(decay_rate, global_step)

Here, we construct the graph as normal:

In [21]:
tf.summary.scalar('learning_rate', learning_rate)
tf.summary.scalar('global_step', global_step)
merged = tf.summary.merge_all() # Merges all summaries collected in the default graph

The first two lines create two summary ops in the graph that will evaluate the learning_rate and global_step value and write them to a TensorBoard compatible binary log string called a summary.

The third line creates a node that merges all summaries collected in the default graph. In the execution phase, you'll need to evaluate the merged node regularly during training (e.g., every 10 mini-batches). This will output a summary that you can then write to the events file using the *`file_writer`*.

In [22]:
import time
logdir = "tf_logs/example01/model-at-{}".format(time.strftime('%Y-%m-%d_%H.%M.%S'))
file_writer = tf.summary.FileWriter(logdir, tf.get_default_graph())

<img src="images/note.gif" width="40" align="left"> Tip: You need to use a different log directory every time you run your program, or else TensorBoard will merge stats from different runs, which will mess up the visualizations. The simplest solution for this is to include a timestamp in the log directory name.

Now's the execution phase: <br>
\- The first line creates a node in the graph that will evaluate the *MSE* value and write it to a TensorBoard compatible binary log string called a summary. Then you need to update the execution phase to evaluate the *`mse_summary`* node regularly during training
(e.g., every 10 mini-batches). This will output a summary that you can then write to the events file using
the *`file_writer`*. Here is the updated code:

In [23]:
with tf.Session() as sess:
    global_step.initializer.run()
    for i in range(50):
        merged_ = merged.eval()
        file_writer.add_summary(merged_)

<img src="images/warning.png" width="40" align="left"></img> **Warning**: *In real-world application logging training stats at every single training step would significantly slow down training; instead, one should log at regular interval, such as after each 200 iterations*.

Finally, you want to close the FileWriter at the end of the program:

In [24]:
file_writer.close()

##### <span style="color:#0b486b"> Using TensorBoard server to visualize </span>

Great! Now it’s time to fire up the TensorBoard server. You need to activate your virtual environment
if you created one, then start the server by running the *`tensorboard`* command, pointing it to the root log
directory. This starts the TensorBoard web server, listening on port 6006 <br> <br>
- Open command line, nevigate to the folder of this tute and run **> tensorboard --logdir tf_logs**
- Open your browser and go to https://localhost:6006. Welcome to
TensorBoard! In the Scalars tab, you'll see *`global_step`* and *`learning_rate`*: <br><br>

<img src='images/learning_rate.png' width=300>

## <span style="color:#0b486b"> II. Understanding TensorFlow 2.x </span>

### <span style="color:#0b486b"> II.1. Advancements of TensorFlow 2.x </span>

In TF 1.x, we need to declare a computational graph manually and create session to query node values. This is different from an imperative and high-level programing language such as Python, which is much easier to work with and more dynamic. TF 2.x brings TF to closer to an imperative and high-level programming language such as Python, thereby making the task of building up deep learning models more conveniently. This is due to two new features: **eager execution** and **AutoGraph**.
- **Eager execution**: you still have a graph, but you can define, change, and execute nodes on-the-fly, with no special session interfaces or placeholders. This is what is called eager execution, meaning that the model definitions are dynamic, and the execution is immediate. Graphs and sessions should be considered as implementation details. In TF 2.x, we do not need to work directly with a computational graph and session.
- **AutoGraph**: AutoGraph takes eager-style Python code and automatically converts it to graph-generating code. So, again, transparently TensorFlow 2.x creates a bridge between imperative, dynamic, and eager Python style programming with efficient graph computations, taking the best of both worlds.

In addition, Keras has been incorporated in and become a part of TF 2.x, which allows us to build up deep learning models comfortably and conveniently.


### <span style="color:#0b486b"> II.2. TensorFlow 2.x's API and architecture</span>

The below image shows the API of TF 2.x. At the lowest level, each TensorFlow operation (op for short) is implemented using highly efficient C++ code. Many operations have multiple implementations called kernels: each kernel is dedicated to a specific device type, such as CPUs, GPUs, or even TPUs (tensor processing units).

<img src='images/TF_API.png' align=center width=600>


The architecture of TF 2.x is shown in the following image. Most of the time your code will use the high-level APIs (especially tf.keras and tf.data); but when you need more flexibility, you will use the lower-level Python API, handling tensors directly. 

<img src='images/TF_Architecture.png' align=center width=600>

### <span style="color:#0b486b"> II.3. Using TensorFlow like NumPy</span>

#### <span style="color:#0b486b"> Tensors and Operations </span>

In [1]:
import tensorflow as tf

In [2]:
t= tf.constant([[1,2,3],[4,5,6]])

In [3]:
print(t.shape)
print(t.dtype)

(2, 3)
<dtype: 'int32'>


In [4]:
t[:,1:]

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [5, 6]])>

In [5]:
t + 10

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[11, 12, 13],
       [14, 15, 16]])>

In [6]:
tf.square(t)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 1,  4,  9],
       [16, 25, 36]])>

In [7]:
print(t)
tf.reduce_sum(t, axis=0)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


<tf.Tensor: shape=(3,), dtype=int32, numpy=array([5, 7, 9])>

In [8]:
tf.transpose(t)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 4],
       [2, 5],
       [3, 6]])>

You will find all the basic math operations you need (`tf.add(), tf.multiply(), tf.square(), tf.exp(), tf.sqrt()`, etc.) and most operations that you can find in NumPy (e.g., `tf.reshape(), tf.squeeze(), tf.tile()`). Some functions have a dif‐ ferent name than in NumPy; for instance, `tf.reduce_mean(), tf.reduce_sum(), tf.reduce_max(), and tf.math.log()` are the equivalent of `np.mean(), np.sum(), np.max() and np.log()`.

#### <span style="color:#0b486b"> Variable</span>

In [9]:
v = tf.Variable(tf.ones([2,3], dtype= tf.float32))
v

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [10]:
v.assign(2*v)
v

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[2., 2., 2.],
       [2., 2., 2.]], dtype=float32)>

In [11]:
v[0,1].assign(10)
v[1,2].assign(20)
v

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[ 2., 10.,  2.],
       [ 2.,  2., 20.]], dtype=float32)>

In [12]:
v.scatter_nd_update(indices=[[0, 0], [1, 2]], updates=[100., 200.])
v

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[100.,  10.,   2.],
       [  2.,   2., 200.]], dtype=float32)>

#### <span style="color:#0b486b"> TF Functions and Graph</span>

In [13]:
def cube(x):
    return x**3

In [14]:
cube(3)

27

In [15]:
cube(tf.constant(2))

<tf.Tensor: shape=(), dtype=int32, numpy=8>

In [16]:
tf_cube = tf.function(cube)
tf_cube

In [17]:
tf_cube(tf.constant(2))

<tf.Tensor: shape=(), dtype=int32, numpy=8>

In [18]:
@tf.function
def tf_cube(x):
    return x**3

In [19]:
tf_cube

In [20]:
tf_cube.python_function(2)

8

#### <span style="color:#0b486b"> AutoGraph and Tracing</span>
To fulfill the autograph feature, TF 2.x need to parse and analyze Python functions to capture all the control flow statements, such as *for loops, while loops*, and *if* statements, as well as *break, continue*, and *return statements*. 

After analyzing the function’s code, AutoGraph outputs an upgraded version of that function in which all the control flow statements are replaced by the appropriate TensorFlow operations, such as `tf.while_loop()` ,`for loops`, and `tf.cond()` for if statements. 

In the below figure, the function `sum_square(n)` is analyzed and transformed to the function `tf_sum_square(n)`, which is more convenient to be executed in the graph mode in the next step. When you invoke the former function: `sum_square(tf.constant(5))` for example, the upgraded function `tf__sum_squares()` function will be called with a symbolic tensor of type int32 and shape []. The function will run in graph mode, meaning that each TensorFlow operation will add a node in the graph to represent itself and its output tensor(s) (as opposed to the regular mode, called eager execution, or eager mode). In the following figure, you can see the `tf__sum_squares()` function being called with a symbolic tensor as its argument (in this case, an int32 tensor of shape []) and the final graph being generated during tracing. 

<img src='images/AutoGraph.png' align=center width=700>

---
### <span style="color:#0b486b"> <div  style="text-align:center">**THE END**</div> </span>